# ------------------------------------------------------------
# oauth2-proxy Secret
# ------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: easyshop-hack
type: Opaque
stringData:
  # Paste from Keycloak client "easyshop-proxy" -> Credentials -> Client Secret
  OAUTH2_PROXY_CLIENT_SECRET: "hCFhCS12dRbKzn07eQoTlfHXNkbUkI6b"

  # Generate using:
  # openssl rand -base64 32
  OAUTH2_PROXY_COOKIE_SECRET: "ilsAgOYE0h_dI6qnYDDdis2xKDxqqxvgSPdHs-oPoPE"
                                                                                  