apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
  namespace: cka-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: httpd
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
