apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: keycloak
type: Opaque
stringData:
  POSTGRES_PASSWORD: password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  keycloak.json: |
    