apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/component: exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  selector:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/component: exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
